location       = "Central US"
rg_name        = "terraformBackend"
asa_name       = "retrogametf"
asc_name       = "terraform-state"
asc_vault_name = "terraform-state-vault"
asc_test_name = "terraform-state-test"