name: Deploy Infrastructure in Azure

# on: workflow_dispatch
on:
   push:
    branches:
      - "test"

jobs:

  Infrastructure:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform/infrastructure
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      ACR_USER: FOO

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Format
        run: terraform fmt
        
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -lock=false
        
      - name: Terraform Apply
        run: terraform apply --auto-approve -lock=false
    

      - name: Export output values to env variables
        run: |
          terraform output -json > terraform-output-values
          cat  terraform-output-values | grep value > terraform-sed-aux
          sed 's/"value": "//' terraform-sed-aux >  terraform-output-values
          sed 's/.$//'  terraform-output-values > terraform-sed-aux
          sed 's/ //g' terraform-sed-aux >  terraform-output-values
          ACR_SERVER=$(sed -n 1p  terraform-output-values)
          ACR_USER=$(sed -n 2p  terraform-output-values)
          ACR_PASSWORD=$(sed -n 3p  terraform-output-values)
          export ACR_SERVER
          export ACR_USER
          export ACR_PASSWORD
          # rm terraform-output-values terraform-sed-aux

      - name: Proof
        run: echo $ACR_USER

      - name: Build the Docker image
        run: docker build -t pacman-app .

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: $ACR_USER
          # Container registry password
          password: $ACR_PASSWORD
          # Container registry server url
          login-server: $ACR_SERVER
        
      - name: Proof
        run: echo $ACR_USER

      - name: Proof
        run: echo ${{ env.ACR_USER }}


      - name: Tag Docker image
        run: docker tag pacman-app echo ${{ env.ACR_USER }}/pacman-app
      
      - name: Push Docker image into ACR
        run: docker push $ACR_SERVER/pacman-app     

          

  Cluster:
    runs-on: ubuntu-latest
    needs: Infrastructure

    defaults:
      run:
        working-directory: ./helm

    steps:

      - uses: actions/checkout@v2

      - name: Install Helm
        uses: Azure/setup-helm@v1

        with:
          version: v3.7.1

      - name: Get AKS Credentials
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZ_CREDS }}
          # Resource Group Name
          resource-group: rg-retro_pacman
          # AKS Cluster Name
          cluster-name: kc_retro_pacman
      - name: Run Helm Deploy
        run: |
          helm upgrade \
            --install \
            --create-namespace \
            --atomic \
            --wait \
            --namespace pacman \
            retropacmanapp \
            . \
            --set username=$MONGO_AUTH_USER \
            --set password=$MONGO_AUTH_PWD
        env:
          MONGO_AUTH_USER: ${{ secrets.MONGO_USER }}
          MONGO_AUTH_PWD: ${{ secrets.MONGO_PWD }}