name: Deploy Vault Infrastructure in Azure

on: workflow_dispatch

jobs:

  DeployInfra:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform/vault
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Format
        run: terraform fmt
        
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var admin_password=${{secrets.VM_PASSWORD}} -lock=false
        
      - name: Terraform Apply
        run: terraform apply -var admin_password=${{secrets.VM_PASSWORD}} --auto-approve -lock=false

      - name: Get public-ip
        run: |
          terraform output -json > public-ip
          cat  public-ip | grep value > terraform-sed-aux
          sed 's/"value": "//' terraform-sed-aux >  public-ip
          sed 's/.$//'  public-ip > terraform-sed-aux
          sed 's/ //g' terraform-sed-aux >   public-ip
          rm terraform-sed-aux
      
      - name: Add ip to inventory
        run: |
          cat public-ip >> aux
          echo ' ansible_user=azureuser ansible_ssh_pass=' >> aux
          echo ${{secrets.VM_PASSWORD}} >> aux
          cat aux | tr -d '\n' >> ./ansible/inventory.in
          rm aux
      
      - name: Debug
        run: cat ./ansible/inventory.in

      - name: Run Ansible
        run: ansible-playbook ./ansible/vault-configure.yml -i ./ansible/inventory.in
  

        
        